### ISSUE TITLE
希望能有cordova插件支持Android和IOS，如果可以也支持uwp吧

### ISSUE THREAD

**Issue by ghostgzt** [wendux/fly#1]
希望能有cordova插件支持Android和IOS，如果可以也支持uwp吧，在这方面，这项目用处很大！

**Comment by wendux** [comment]
我并没用过cordova，希望用过cordova的同学贡献力量啊。

**Comment by GeoffZhu** [comment]
cordova也是webview，直接就可以当浏览器用，不需要单独实现

**Comment by ghostgzt** [comment]
当然不一样，webview的http请求限制很多，Cordova插件就是写原生部分

**Comment by GeoffZhu** [comment]
恩，需要改ua之类的确实浏览器改不了。。。。

**Comment by wendux** [comment]
fly是js端的库，cordova的engine 官方不会提供，需要开发者自己去实现
