### ISSUE TITLE
请求添加对 PUT 和 DELETE 等 HTTP 方法的支持

### ISSUE THREAD

**Issue by tonghuashuo** [wendux/fly#10]
鉴于 Restful API 的广泛使用，仅仅 GET 和 POST 似乎还不太够，Fly 用起来很爽，如果能加上对 PUT 和 DELETE 等 HTTP 方法的支持就更好了。

PS：本以为可以通过`request()`方法手动发起，结果看到非 GET 请求只有 `engine.open('POST')`，只好来提 Issue 了

**Comment by wendux** [comment]
[fixed](https://github.com/wendux/fly/commit/4acd27bc2910b459fb21de87f860c3f68a2cbf5b)
npm 0.2.3

**Comment by tonghuashuo** [comment]
谢谢，看到在`engine.open()`处开放了用于其它方法的限制。

可否在 API 层面上直接加上`put()`、`delete()`、`patch()`等快捷方法，这样使用起来会更加直观和方便，目前只能通过`request()`来调用。

**Comment by wendux** [comment]
已支持  flyio npm version >=0.2.4
