### ISSUE TITLE
request:fail length8192; index=8192是什么错误？

### ISSUE THREAD

**Issue by fernandoxu** [wendux/fly#100]
很奇怪，我的小程序有一个接口偶尔会出现这个报错，换了小程序的原生请求就再也没出现过。

![_20180726115242](https://user-images.githubusercontent.com/20871468/43240720-7fc33a42-90ca-11e8-9036-6eeb9c0eeff9.png)

**Comment by wendux** [comment]
这得有详细的信息来还原现场，这一张图也没办法排查


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by fernandoxu** [comment]
@wendux 现在用原生的请求也会偶尔出现这个报错了，是小程序请求的问题。请教一下fly怎么配置请求出错后重试？🤭

**Comment by wendux** [comment]
@fernandoxu 可以参考拦截器的示例


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
