### ISSUE TITLE
mpvue中使用Fly，post请求network里面已经发送数据成功，而后台却接收不到

### ISSUE THREAD

**Issue by lisun0459** [wendux/fly#101]
用post方法，发送的数据可以console出来，控制台network里面Request payload里也显示了数据，但后台接收到的是空。

**Comment by davidlin88** [comment]
可能请求头没有设置正确，用postman测试下

**Comment by wendux** [comment]
@lisun0459 如果控制台显示了发送的数据，那么就是发送成功了，你看看你后台接收数据的方式或者编码是不是正确，fly默认以json方式发送数据。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
