### ISSUE TITLE
小程序中使用需要添加请求头，设置fly.config.headers没有作用

### ISSUE THREAD

**Issue by Leeehuixian** [wendux/fly#103]
![image](https://user-images.githubusercontent.com/17973371/43318390-306b7de2-91d3-11e8-98ff-bf823e725f51.png)

**Comment by wendux** [comment]
首先确保vpncode是否有值，然后请在调试窗口截图实际的请求头，贴出来


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Leeehuixian** [comment]
好的，谢谢，问题找到了，依赖引入错误导致的
