### ISSUE TITLE
是不是不支持patch方法，一直报方法不合法

### ISSUE THREAD

**Issue by Jackieboy29** [wendux/fly#104]

**Comment by wendux** [comment]
@Jackieboy29 小程序中吗？我记得小程序Api不支持patch方法，你可以看一下小程序文档核对一下


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Jackieboy29** [comment]
![image](https://user-images.githubusercontent.com/21135807/43376779-2d7d9b6a-93ef-11e8-9a80-a3c0f9306c20.png)
是在小程序中，文档看到了，感谢
