### ISSUE TITLE
引用拦截器中异步操作请求token的demo，报错，求指教！！！

### ISSUE THREAD

**Issue by Leeehuixian** [wendux/fly#108]
//import fly from "../index";
    var csrfToken = "";
    //定义公共headers
    fly.config.headers = {"x-tag": "flyio"}
    fly.config.baseURL = "http://www.dtworkroom.com/doris/1/2.0.0/"
    var newFly = new Fly;
    newFly.config = fly.config;
    var log = console.log
    fly.interceptors.request.use(function (request) {
        log(`发起请求：path:${request.url}，baseURL:${request.baseURL}`)
        if (!csrfToken) {
            log("没有token，先请求token...");
            //锁定当天实例，后续请求会在拦截器外排队
            fly.lock();
            return newFly.get("/token").then((d) => {
                request.headers["csrfToken"] = csrfToken = d.data.data.token;
                log("token请求成功，值为: " + d.data.data.token);
                log(`继续完成请求：path:${request.url}，baseURL:${request.baseURL}`)
                return request
            }).finally(() => fly.unlock()) //解锁后，会继续发起请求队列中的任务
        } else {
            request.headers["csrfToken"] = csrfToken;
        }
    })
    //  response interceptors
    fly.interceptors.response.use(
        function (response) {
            log("interceptors.response", response)
            //验证失效
            if (response.data.data.tokenExpired) {
                log("token失效，重新请求token...");
                this.lock(); //锁定响应拦截器
                return newFly.get("/token")
                    .then((d) => {
                        csrfToken = d.data.data.token;
                        log("token已更新，值为: " + csrfToken);
                    })
                    .finally(() => this.unlock())
                    .then(() => {
                        log(`重新请求：path:${response.request.url}，baseURL:${response.request.baseURL}`)
                        return fly.request(response.request);
                    })
            } else {
                return response.data.data;
            }
        },
        function (err) {
            log("error-interceptor", err)
        }
    )
    fly.get("/test?tag=1")
        .then(function (d) {
            log("请求成功:", d)
        }).catch(function (e) {
        log("请求失败", e)
    })
    fly.get("/test?tag=2")
        .then(function (d) {
            log("请求成功:", d)
        }).catch(function (e) {
        log("请求失败", e)
    })
    fly.get("/test?tag=3")
        .then(function (d) {
            log("请求成功:", d)
        }).catch(function (e) {
        log("请求失败", e)
    })

以下是log：

![image](https://user-images.githubusercontent.com/17973371/43382402-3a0b8ebc-940a-11e8-9bc5-2ef499063641.png)

![image](https://user-images.githubusercontent.com/17973371/43382429-54a7f224-940a-11e8-877b-c83aedd43539.png)

疑问有两个：
1、console.log()错误原因
2、token请求成功，并且有值，为什么请求头中看不到添加的csrfToken 内容

**Comment by wendux** [comment]
`Promise.finally` API较新，小程序还不支持，你可以使用pollyfill 或者在then和catch中分别都处理一下，这个问题其它issue里面都有，提issue之前应该先看看


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
