### ISSUE TITLE
拦截器中执行异步任务 是否支持 请求2依赖 请求1的结果作为参数

### ISSUE THREAD

**Issue by NxGreen** [wendux/fly#109]
例如：请求/gettoken 时，如果发现没有 token,就拦截请求test2,test3。当成功获取 token，把 /gettoken的值作为参数传递给 test2,test3继续发送请求。能否实现这种情况？

fly.get("/gettoken")
    .then(function (d) {
        log("请求成功:", d.token)
    }).catch(function (e) {
    log("请求失败", e)
})
fly.get("/test2?tag=2",{token:token})
    .then(function (d) {
        log("请求成功:", d)
    }).catch(function (e) {
    log("请求失败", e)
})
fly.get("/test3?tag=3",{token:token})
    .then(function (d) {
        log("请求成功:", d)
    }).catch(function (e) {
    log("请求失败", e)
})

**Comment by shiweiqi19930328** [comment]
@NxGreen 
fly.lock()  这个api了解一下

**Comment by wendux** [comment]
可以参考文档中拦截器部分token续期的示例


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by NxGreen** [comment]
@shiweiqi19930328 @wendux  文档中的拦截器是 在所有的请求都需要在header中设置一个token。但是我现在想要的是 把请求1的结果 以 params 参数的形式，放在请求2的data数据中传送给后台，不设置 请求头 header
