### ISSUE TITLE
在get方法传递数组参数时，是否支持[paramsSerializer]

### ISSUE THREAD

**Issue by ccfish86** [wendux/fly#114]
之前在使用axios时，可以通过以下方式，把请求中的`/api/portal/?channelId%5B%5D=1&channelId%5B%5D=2` 格式化为`/api/portal/?channelId=1&channelId=2`以便于后台接收参数，请问在flyio中是否也可以这么做。
```
paramsSerializer: function (params) {
    return qs.stringify(params, {arrayFormat: 'repeat'})
  }
```

**Comment by wendux** [comment]
目前框架内没有，但可以在拦截器中去做


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
