### ISSUE TITLE
接口返回401，响应内容为非json字符串时报错

### ISSUE THREAD

**Issue by ruixiu** [wendux/fly#118]
调用后台接口，响应状态码为401，响应内容为非json字符串（如：请重新登录系统），fly框架解析报错。请问有没有办法解决？【老接口无法修改】

**Comment by shiweiqi19930328** [comment]
附议，能否内部catch掉转化json时的错误

**Comment by wendux** [comment]
如果响应的contentType不是json的话，fly是不会去自动转的啊，你的接口是不是contentType为json但数据却不是json数据？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ruixiu** [comment]
个人觉得是不是可以优先对状态码进行验证，然后再处理响应内容

**Comment by wendux** [comment]
@ruixiu 不行，因为状态码并非表示成功的状态时，依然可以返回响应体内容，所以内容解析应该是和状态码无关的。如果你不希望自动解析，可以将parseJson设为false。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by shiweiqi19930328** [comment]
为什么转JSON时不添加个try catch呢？

**Comment by wendux** [comment]
@shiweiqi19930328 因为在后台声明自己返回内容是json但返回的内容却不是json的情况下框架应该将错误出以供开发者排错。如果不期望自动转换json, 可以手动将parseJson 置为false.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by abitwhy** [comment]
> @ruixiu 不行，因为状态码并非表示成功的状态时，依然可以返回响应体内容，所以内容解析应该是和状态码无关的。如果你不希望自动解析，可以将parseJson设为false。
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

既然 `status`  的含义并非仅限于出错状态，那么是否考虑给响应拦截器中的 `response` 对象添加 `status ` 字段，而不是屏蔽它。

**Comment by abitwhy** [comment]
看到您在 `engine.setAdapter` 的回调的参数中提供了 `status` 字段，那能否谈谈您在默认 `engine` 屏蔽它的原因呢？
