### ISSUE TITLE
请问如何设置 Content-Type

### ISSUE THREAD

**Issue by lilonghe** [wendux/fly#12]
没有找到相关文档
如下参考 fetch 的配置方法似乎也没用 ?
```
headers: { 'Content-Type': 'application/json; charset=utf-8'}
```

**Comment by wendux** [comment]
首先，请确保并fly的npm版本大于>=0.2.6
设置的地方有三个地方：
1. fly.config.headers={}
2. options中
3. 拦截器中
但是只有当请求的数据类型是字符串时，设置Content-Type才有效
