### ISSUE TITLE
mpvue中，请求后端接口经过重定向后cookie没有同步，怎么处理配置呢？

### ISSUE THREAD

**Issue by supremeJY** [wendux/fly#122]
- mpvue中，请求后端接口经过重定向后cookie没有同步，怎么处理配置呢？

**Comment by wendux** [comment]
@supremeJY  这个要看微信原生Api是不是支持，fly最终也是调用的微信Api


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
