### ISSUE TITLE
在浏览器环境中，set-cookie有两个值，但weex(安卓)下只能看到一个值

### ISSUE THREAD

**Issue by ccfish86** [wendux/fly#125]
请确认是哪儿的问题，如果短时间解决不了，只能先保留一个了
![image](https://user-images.githubusercontent.com/15622514/45008065-342d3a00-b033-11e8-8700-d2d8b4f331d4.png)
![image](https://user-images.githubusercontent.com/15622514/45008134-7f474d00-b033-11e8-9e12-900fc6b2fa56.png)

**Comment by wendux** [comment]
weex中是有两个值的，没问题，headers["set-cookie"]是一个数组，数组toString之后就是你对话框弹出的结果，你可以按照数组来取。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ccfish86** [comment]
weex要支持cookie可能还是改android的HttpAdapter实现比较好。
