### ISSUE TITLE
为什么用了es6的class类的语法，为什么不用let和const

### ISSUE THREAD

**Issue by nokisnojok** [wendux/fly#129]
源码很难解析

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
因为在babel编译后，let还是会被转为var,而let本身支持块级作用域，编译后是通过闭包来实现，当时担心如果babel优化不好，可能会在不期望块级作用域的地方生成块级作用域，这可能会增大体积, 所以才用var， 这样生成的代码是可期望的，也许这样做的意义并不会太大，但能避少一个字节是一个字节。。之所以使用class是因为在创建类时要比通过function+ prototype 来实现跟简洁，主要考虑的是表现力。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by nokisnojok** [comment]
如果使用者希望打包之后的代码在es6的环境允许呢？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
