### ISSUE TITLE
微信小程序中FormData问题

### ISSUE THREAD

**Issue by peirancao** [wendux/fly#13]
`fly.interceptors.request.use((config, promise) => {
  if (config.method === 'POST') {
    let data = new FormData()
    for (let key in config.body) {
      data.append(key, config.body[key])
    }
    config.body = data
  }
  console.log(config)
  return config
})`
我在拦截器里面处理POST数据 但是不能正常工作 request header content-type 还是 json 是哪里有问题吗？

**Comment by wendux** [comment]
由于微信小程序 `wx.request` 发送的数据不支持FormData， 故不能在微信小程序中直接使用FormData。详情请参考：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html#wxrequestobject

如果你的需求是不想以json格式提交数据的话，您需要自己编码query参数：
```javascript
  fly.post("","xx=a&bb=d")
```
fly会在发送的数据是字符串时将 Content-type设置为application/x-www-form-urlencoded

**Comment by LancelotLewis** [comment]
@wendux 微信文档里给的介绍是，手动设置content-type为application/x-www-form-urlencoded，程序会自动将json数据转换为 query参数，但是用flyio貌似不行

**Comment by wendux** [comment]
是的，flyio RequestBody默认以json形式传递数据，如果非要以formdata编码传递的话，需要手动编码，你可以在发起请求时编码：
```javascript
   fly.post("","xx=a&bb=d") 
```
也可以在拦截器中统一编码，大致的代码如下：
```javascript
fly.interceptors.request.use((config, promise) => {
    if (config.method === 'POST' && typeof config.body==="object") {
        let data ="";
        for (let key in config.body) {
            if(data){
                data+="&"
            }
            data+=encodeURIComponent(key)+"="+encodeURIComponent(config.body[key])
        }
        config.body = data
    }
})
//发起请求
fly.post("",{xx:"a",bb:"d"}) 
```

**Comment by LancelotLewis** [comment]
@wendux 想过这样处理，但是好像有个问题。不论修改最后的`config.body`为任何值，post请求的form data 其实都是 fly.post 传进去的值

**Comment by wendux** [comment]
用最新版试试
