### ISSUE TITLE
使用flyio发出的GET请求也会先发一个预检请求OPTIONS

### ISSUE THREAD

**Issue by Claiyre** [wendux/fly#134]
## version
```
"flyio": "^0.6.1",
```
## code
```
fly.get('http://wanproxy.127.net/lbs', {
  version: '1.0',
  bucketname: 'vod0j9f7jwb'
})
.then(res => console.log('res', res))
.catch(err => console.log(err))
```
![image](https://user-images.githubusercontent.com/18069718/46070108-92bb8300-c1af-11e8-8b84-2025a3c7e456.png)

使用原生XMLHttpRequest发出同样的get请求便不会发OPTIONS
![image](https://user-images.githubusercontent.com/18069718/46070153-ab2b9d80-c1af-11e8-9e66-c129027c3a51.png)

这个接口是第三方的，发预检请求便会出错，若直接是get请求则不会

**Comment by wendux** [comment]
你fly中有没有设置自定义header? 跨域请求含有自定义header的话就会发起预检，即使是get请求。 你对比一下fly和原生的request header看看有什么区别。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Claiyre** [comment]
@wendux 
我没有自定义header，fly替我定义了Content-Type 😛

![image](https://user-images.githubusercontent.com/18069718/46207270-5deb2f80-c359-11e8-883a-4b7d035bed1d.png)

是否可以在 isGet 时也 delete headers.contentType呢？

BTW，你写的代码真好看

**Comment by wendux** [comment]
嗯 get请求时content type没有意义  节后会删掉


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
