### ISSUE TITLE
请问一下在小程序里能使用flyio.clear这个方法吗？

### ISSUE THREAD

**Issue by spencer1994** [wendux/fly#135]
在小程序中的A页面同时发起了4个请求，都判断了有没有token，若没有则需要去拿token。

在没有token的情况下调用fly.lock()后去小程序登录授权获取token。

在登录授权后，调用了flyio.clear()、flyio.unlock()。

在请求token成功后然后重定向到A页面，此时A页面的接口没有再触发。

初步判断是不是flyio.clear()在小程序里面使用会有点问题？

请问一下在小程序里能使用flyio.clear这个方法吗？

我描述的清楚了吗？没有的话我可以再补充！谢谢

**Comment by wendux** [comment]
请求都跨页面了？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by spencer1994** [comment]
@wendux 是的。
![image](https://user-images.githubusercontent.com/19463934/46183339-1fc32100-c303-11e8-8bef-f1ae1dbc6b7b.png)
![image](https://user-images.githubusercontent.com/19463934/46183355-2b164c80-c303-11e8-8c76-e171b2251b20.png)
在请求拦截器中拦截了，然后跳转了页面去获取用户信息，获取完后清除掉请求队列，再重定向至之前的页面。在微信模拟器上重定向到之前的页面是可以请求接口的。但是在手机上就请求不了接口。

**Comment by spencer1994** [comment]
![image](https://user-images.githubusercontent.com/19463934/46186744-b77c3b80-c312-11e8-861e-590e06d39678.png)
很奇怪，跳转了页面就不行，写到一个页面就可以了。
看起来我在另外一个页面import的应该是同一个对象才对呀。
