### ISSUE TITLE
在mpvue用flyio发送 post请求  spring boot后端接收的竟然是get请求

### ISSUE THREAD

**Issue by DreamPWJ** [wendux/fly#136]
这种情况不是必然  是小概率事件  请求的是/user路径  发现后端接收的是/user/  多了一个/
Request method 'GET' not supported

**Comment by wendux** [comment]
你把请求的baseurl和post的path贴出来


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by DreamPWJ** [comment]
这个不是必然性的  是小部分用户有这个问题  https://dingshi2.com/user 之前是这个post请求  后来修改成https://dingshi2.com/user/login 还没验证是否是path路径的问题

**Comment by 283010247** [comment]
我遇到过，这是因为你加了大括号，fly.post({'wxapp/user/set-union'})写成这样子就会变成get请求

**Comment by DreamPWJ** [comment]
@283010247  不是这个原因  没有大括号  
/**
 * 用户登录
 */
const login = (user) => {
  return http.post(`user/login`, user)
}

**Comment by wendux** [comment]
会不会是后台接口问题，你接口的完整地址能贴出来吗？

**Comment by DreamPWJ** [comment]
@wendux 不会是后端接口的问题的  后端已经经过大量的项目验证了  fly第一次用

**Comment by DreamPWJ** [comment]
这个问题之前是随机性的 没法复现啊

**Comment by DreamPWJ** [comment]
随机性的mpvue整合flyio  版本0.6.2  明确前端传入的是post 后台尽然是获取的是get 说明前端请求有问题  后端项目都是经过验证的@wendux
