### ISSUE TITLE
Web发起的请求会自动带上Cookie传给adapter

### ISSUE THREAD

**Issue by sunzongzheng** [wendux/fly#137]
如题，我这边看源码里面有这么一段
![image](https://user-images.githubusercontent.com/12635613/46582688-8a036080-ca7d-11e8-9f83-7c8f4b67e2da.png)
应该是这段导致会覆盖我手动设置的cookie，请问怎么解？我不希望自动发送的cookie覆盖掉我手动设置的cookie，这个属于篡改了我的请求。
而且我发出的是跨域请求，配置加上withCredentials: false也无效

**Comment by wendux** [comment]
请升级到0.62重试

**Comment by sunzongzheng** [comment]
解决了，thx~
