### ISSUE TITLE
如何去掉真实请求前的options请求

### ISSUE THREAD

**Issue by xiangmeng** [wendux/fly#140]
我用最简单的方法访问服务器地址，但是真实调用前，总是会发送一个options请求到服务器。后台不支持该请求类型，导致真实请求无法执行。请问，如何去掉options请求？
![image](https://user-images.githubusercontent.com/3375712/46792032-f380b900-cd74-11e8-941d-011aeb8efd62.png)

代码是：
![image](https://user-images.githubusercontent.com/3375712/46792060-01363e80-cd75-11e8-843f-b77f74fe222f.png)

**Comment by wendux** [comment]
你的请求是不是跨域的？对于非简单的跨域请求，浏览器都会先发起一次预检请求(options)，详情可以参考MDN文档。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
