### ISSUE TITLE
mpvue 编译小程序端报错 this.engine is not a constructor

### ISSUE THREAD

**Issue by jimengchao** [wendux/fly#141]
小程序端下提示错误 网页端正常
![image](https://user-images.githubusercontent.com/9922823/46862866-732b8800-ce48-11e8-95fe-2c07cbb2715c.png)

代码
request.js
```
import flyio from 'flyio'
flyio.interceptors.request.use((config, promise) => {
  return config
})

flyio.interceptors.response.use(
  (response, promise) => {
    return promise.resolve(response.data)
  },
  (err, promise) => {
    if (err) {
      wx.showToast({
        title: err.message,
        icon: 'none'
      })
    }
    return promise.resolve()
  }
)

export default flyio
```

index.vue
```
 flyio.get('url').then(data => {
                console.log(data)
            }).catch(err => {
                console.log(err);
            })
```

**Comment by mdsb100** [comment]
不用拦截器好像不会错

**Comment by mdsb100** [comment]
我也复现了

**Comment by mdsb100** [comment]
@jimengchao 我知道了，你没设置baseUrl。直接请求path加上拦截器就能复现这个问题。

**Comment by jimengchao** [comment]
> @jimengchao 我知道了，你没设置baseUrl。直接请求path加上拦截器就能复现这个问题。

但是我不需要 设置baseUrl 我的接口 会有多个域名的存在。

**Comment by windhc** [comment]
这个问题解决了没

**Comment by gengchen528** [comment]
同问这个问题怎么解决的

**Comment by jimengchao** [comment]
> 同问这个问题怎么解决的

小程序引入是 `require("flyio/dist/npm/wx");new Flyio()`  
网页端 直接 `require('flyio')`

**Comment by gengchen528** [comment]
> @gengchen528 我是 `new Flyio({})` 不能传空的obj

搞定了，我是因为引入的时候引错了，小程序引入是 `const Fly = require("flyio/dist/npm/wx"); const fly = new Fly() `才可以的
