### ISSUE TITLE
小程序缺少responseType配置

### ISSUE THREAD

**Issue by LiangFuzhi** [wendux/fly#150]
`//微信小程序适配器
module.exports = function (request, responseCallback) {
    var con = {
        method: request.method,
        url: request.url,
        dataType: request.dataType || undefined,
        header: request.headers,
        data: request.body || {},
// 加上这句
        responseType: request.responseType || 'text',
        success: function success(res) {
            responseCallback({
                statusCode: res.statusCode,
                responseText: res.data,
                headers: res.header,
                statusMessage: res.errMsg
            });
        },
        fail: function fail(res) {
            responseCallback({
                statusCode: res.statusCode || 0,
                statusMessage: res.errMsg
            });
        }
    };
    wx.request(con);
};`

**Comment by sonicsunsky** [comment]
小程序端设置options中的reponseType为arrayBuffer无效，返回数据类型不是ArrayBuffer是String,小程序亲测有bug，希望增加对小程序端reponseType的兼容
