### ISSUE TITLE
Can't import flyio to miniprogram by npm.

### ISSUE THREAD

**Issue by AnyMoe** [wendux/fly#156]
I import flyio by npm to miniprogram in this way.
```
var Fly = require("flyio/dist/npm/wx");
var fly = new Fly; 
```
Then the wechatdevtools console show me the following error messages.

>  thirdScriptError 
>  sdk uncaught third Error 
>  module "flyio/dist/npm/wx" is not defined 
>  Error: module "flyio/dist/npm/wx" is not defined

**Comment by AnyMoe** [comment]
The flyio/dist/npm/wx.js does not exist after building npm (构建npm) according to WeChat official documentation.


https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

**Comment by wendux** [comment]
please update to v0.65 , and try as follows:
```javascript
//var Fly = require('../../miniprogram_npm/flyio/index')
import Fly from '../../miniprogram_npm/flyio/index'
var fly = new Fly();
...
```

**Comment by andypinet** [comment]
`//微信小程序入口
var _Fly = __webpack_require__(2);
var EngineWrapper = __webpack_require__(1);
var adapter = __webpack_require__(6);
var wxEngine = EngineWrapper(adapter);
module.exports = function (engine) {
    return new Fly(engine || wxEngine);
};`

这段代码写错了

**Comment by wendux** [comment]
此问题已解决，请升级至0.6.6重试
