### ISSUE TITLE
 使用mpvue，npm引入，报错 Fly is not defined

### ISSUE THREAD

**Issue by JayLee2** [wendux/fly#159]
这是我引入的方式import Fly from 'flyio/dist/npm/wx'，后来我修改源码，
在791行左右
return new _Fly(engine || wxEngine);
Fly前面加了一个_,

**Comment by Luooojunnn** [comment]
不要new 就不报错了

**Comment by Luooojunnn** [comment]
你好，怎么解决的？

**Comment by DestinyHunter** [comment]
同样 .0.6.5 版本有问题

**Comment by DestinyHunter** [comment]
796 行 var _Fly    多了一个_

**Comment by DestinyHunter** [comment]
786

**Comment by Chen-WeiZhen** [comment]
我醉了，怪不得昨天好好的，今天gg了，害了我一小时

**Comment by Chen-WeiZhen** [comment]
> 791行 Fly前面缺少一个下划线，或者786行多了一个下划线

上个图，大兄弟，没找到呢

**Comment by JayLee2** [comment]
![1543548599 1](https://user-images.githubusercontent.com/31609655/49266996-4fbdaa80-f493-11e8-850a-07c0aee0907d.jpg)

**Comment by JayLee2** [comment]
![1543548662 1](https://user-images.githubusercontent.com/31609655/49267039-72e85a00-f493-11e8-9737-9f09f476fc15.jpg)

**Comment by navcat** [comment]
"flyio": "0.6.4"  这样可以解决

**Comment by wendux** [comment]
此问题和#156  是同一问题，已解决，请升级至0.6.6重试
