### ISSUE TITLE
微信小程序引入报错

### ISSUE THREAD

**Issue by zhangzhenfei** [wendux/fly#162]
var _Fly = __webpack_require__(2);
var EngineWrapper = __webpack_require__(1);
var adapter = __webpack_require__(6);
var wxEngine = EngineWrapper(adapter);
module.exports = function (engine) {
    return new Fly(engine || wxEngine);
};

这里应该是` return new _Fly(engine || wxEngine);`

**Comment by wendux** [comment]
此问题和#156  是同一问题，已解决，请升级至0.6.6重试
