### ISSUE TITLE
微信小程序引入错误  查看源码是因为变量名写错了  能尽快改一下吗？

### ISSUE THREAD

**Issue by kemplaw** [wendux/fly#164]
一下是源代码错误的地方。
//微信小程序入口
        var _Fly = __webpack_require__(2);
var EngineWrapper = __webpack_require__(1);
var adapter = __webpack_require__(6);
var wxEngine = EngineWrapper(adapter);
module.exports = function (engine) {
    return new Fly(engine || wxEngine);
};

**Comment by wendux** [comment]
此问题和#156  是同一问题，已解决，请升级至0.6.6重试
