### ISSUE TITLE
Fly is not defined

### ISSUE THREAD

**Issue by Dycodeboy** [wendux/fly#167]
当和vuex同时使用时 new Fly变量名错误[]
![image](https://user-images.githubusercontent.com/16750803/49461585-f9ec5800-f82e-11e8-9e04-f14388113ea2.png)

**Comment by Dycodeboy** [comment]
> 怎么解决？

将flyio版本改为0.6.4

**Comment by fanfan1280** [comment]
没用。。 版本也改了，源码上面也看了，还是报错。

**Comment by Dycodeboy** [comment]
> 没用。。 版本也改了，源码上面也看了，还是报错。

“flyio”:"0.6.4" 不能有^或者~ 否则会自动更新
删除nodel_modules 中的flyio 项目重新npm install

**Comment by fanfan1280** [comment]
就是这么操作的。nodel_modules整个文件都删除了重新装，都没解决。。

**Comment by Kennersky** [comment]
源码变量名字写错了，最后“_Fly”没有对应好
![tim 20181205171147](https://user-images.githubusercontent.com/2129521/49502834-ebdf1b80-f8b0-11e8-907e-0ea3df31bbb3.jpg)
这两个变量改成一样即可

**Comment by fanfan1280** [comment]
恩，这里我知道。我把之前的整个项目删除了，重新建一个项目，一开始就安装0.6.4版本，又没问题了。至于之前为什么一直报错，我也不知道。 哭唧唧~

**Comment by Dycodeboy** [comment]
> 恩，这里我知道。我把之前的整个项目删除了，重新建一个项目，一开始就安装0.6.4版本，又没问题了。至于之前为什么一直报错，我也不知道。 哭唧唧~

也许是没有清除开发者工具中的js缓存？？？

宁可修改版本号，也不建议修改源码，毕竟打包协作的时候不能每次都修改

**Comment by fanfan1280** [comment]
> > 恩，这里我知道。我把之前的整个项目删除了，重新建一个项目，一开始就安装0.6.4版本，又没问题了。至于之前为什么一直报错，我也不知道。 哭唧唧~
> 
> 也许是没有清除开发者工具中的js缓存？？？
> 
> 宁可修改版本号，也不建议修改源码，毕竟打包协作的时候不能每次都修改

不知道，缓存也反复清理了，，不知道啥原因

**Comment by wendux** [comment]
此问题和#156  是同一问题，已解决，请升级至0.6.6重试
