### ISSUE TITLE
关于报错信息

### ISSUE THREAD

**Issue by hainuo** [wendux/fly#17]
我在使用拦截器的时候，发现报错信息只有一个status 是可用的   我在测试中遇到过 只返回过status 0 的问题，想询问下 ，这一块的处理如何自定义呢？我想能够得到服务器返回的整个body的内容？

**Comment by wendux** [comment]
1. 请先查看文档中“错误处理”部分内容，0代表超时
2. 若是服务器发生错误时，err对象会有一个message属性，对应的是`xhr.statusText`, 如404，大多数服务器会将`statusText` 设为“Not find”, 但这并非标准，有些服务器并不会设置`statusText`，此时`err.message`就为空
3. 不建议API在http返回错误码的时候（如404、500）时再返回内容
4. 如果非要在http 犯回错误码时获取body的内容。你可以使用如下代码：
```javascript
     var request=fly.get("xxx")
     request.then(d=>{}).catch(e=>{
       //打印出body内容
       console.log(request.engine.responseText)
     })
```
注意：fly在发起请求后返回的promise对象中会扩展一个 `engine` 属性，代表当前`的xmlHttpRequest`对象，但此属性不具有传递性，所以你不能在调用 `catch` 或` then` 后再获取 `engine`.
