### ISSUE TITLE
支付宝小程序支持

### ISSUE THREAD

**Issue by ac51300696** [wendux/fly#176]
已提交pr，本地经过测试

**Comment by loewe0202** [comment]
//小程序适配器
module.exports = function (request, responseCallback) {
    var con = {
        method: request.method,
        url: request.url,
        dataType: request.dataType || undefined,
        headers: request.headers,
        data: request.body || {},
        success: function success(res) {
            console.log(res);
            responseCallback({
                status: res.status,
                responseText: res.data,
                headers: res.headers,
                statusMessage: res.errMsg
            });
        },
        fail: function fail(res) {
            console.log(res);
            responseCallback({
                status: res.status || 0,
                statusMessage: res.errMsg
            });
        }
    };
    my.httpRequest(con);
};


//小程序入口
        var _Fly = __webpack_require__(2);
var EngineWrapper = __webpack_require__(1);
var adapter = __webpack_require__(6);
var myEngine = EngineWrapper(adapter);
module.exports = function (engine) {
    return new _Fly(engine || myEngine);
};


改了这两部分，但是请求的时候说my没定义，还需要怎么处理么？

**Comment by ac51300696** [comment]
在支付宝小程序下进行的测试，默认全局有my这个支付的全局对象，有没有做兼容处理

**Comment by loewe0202** [comment]
没有，是需要全局定义my么？该如何处理呢

**Comment by ac51300696** [comment]
天冷，手抖了下打错字了，my在支付宝小程序里是全局对象，不用配置的，我测试的时候是直接在支付宝小程序里面测试的

https://docs.alipay.com/mini/api/network

**Comment by ac51300696** [comment]
🤔🤔🤔这个我应该是写错了。。。不过居然也能跑。。。我记得还截了个图

**Comment by ac51300696** [comment]
我明天重新提交一个pr，顺便附带上我的测试截图

**Comment by ac51300696** [comment]
亲测request在支付宝小程序里面也能🌞🌞🌞，真是个意外的发现，跟微信用的同一个名字，然后改了之后的pr已经提交

**Comment by loewe0202** [comment]
哈哈，你发现了个bug

**Comment by loewe0202** [comment]
我发现了我报错的原因了，是我的编译器的问题，我重新安装了支付宝的编译器就好了

**Comment by rockywu** [comment]
可以尝试使用：https://www.npmjs.com/package/flyio-ext

**Comment by wendux** [comment]
已支持
