### ISSUE TITLE
小程序 原生npm 支持bug

### ISSUE THREAD

**Issue by loewe0202** [wendux/fly#182]
试了下原生的npm 发现官网给的方法报错
var Fly=require("flyio/dist/npm/wx") 
var fly=new Fly

改成下面引用就可以了
var Fly = require("flyio");
var fly = new Fly();

不知道是不是我打开的方式不对。。。。。。

**Comment by wendux** [comment]
示例是直接指向的源文件，能映入就行，也可以把代码拷到小程序目录

**Comment by mario-huang** [comment]
能否把各个端的引入和初始化统一起来。
现在node端TS里面需要：
import Fly from 'flyio'
const fly = Fly
Fly本身已经初始化了。
微信端
import Fly from 'flyio'
const fly = new Fly() // Fly需要new

搞得我们的SDK基于fly，写代码的时候是node环境，但到了微信小程序环境就报错了。
