### ISSUE TITLE
fly拦截器中用.then不执行

### ISSUE THREAD

**Issue by xiyuanma** [wendux/fly#188]
fly.lock(); //锁定响应拦截器，
      return wxLogin().then((res) => {
        console.log(res);
        wx.setStorageSync('code',res.code);
        return res.code;
      })
      .then((res) => {
        console.log(res);
        return fly.get("sso/weixinLogin",{code: res}).then((res) => {
          console.log(res);
          return res;
        })
      })

第二个fly.get不执行

**Comment by lonaking** [comment]
同样遇到这样的 问题 弃坑了
