### ISSUE TITLE
fly.lock锁定的是后面你的待请求队列，当前请求无论成功或失败都会对应一个结果，你可以把你代码贴出来看看。

### ISSUE THREAD

**Issue by JH46666** [wendux/fly#191]
fly.lock锁定的是后面你的待请求队列，当前请求无论成功或失败都会对应一个结果，你可以把你代码贴出来看看。

_Originally posted by @wendux in https://github.com/wendux/fly/issues/146#issuecomment-435338913_

**Comment by JH46666** [comment]
fly
  .interceptors
  .request
  .use(async function (request) {
    let url = request.url;
    if (url.includes('/login')) { //白名单
      return request;
    } else {
      console.log('url', url, cookies)
      if (!cookies.length) { //判断有无cookie
        console.log('没有cookie')
        fly.lock();
        return FlyLogin().then(res => {
          console.log('res', res, cookies);  //res已经有值了，cookies还没有为空
          return request;
        }).finally(() => {
          console.log('这一步还执行')
          // fly.unlock();
        })
      }
      request.headers["Cookie"] = cookies;
      request.headers["x-csrf-token"] = token;
      return request;
    }
  });

**Comment by wendux** [comment]
fly.lock 是锁定后续网路请求, 不包括本次，但拦截器支持异步任务，所以在本次请求发起前我们发现token过期的化，可以先请求token，然后更新token，在将更新后的`request`对象返回，继续本次请求。相当于本次请求中间插了一次更新token的请求。 所以上面代码有两个问题：

1. 在FlyLogin()登录成功后要设置header cookie;
```javascript
 return FlyLogin().then(res => {
   console.log('res', res, cookies); //res已经有值了，cookies还没有为空
  // 登录成功后在这里也要设置header
   request.headers["Cookie"] = cookies;
   return request; //返回request是表示使用这个request对象继续上一次请求
})
```
2. 登录成功后一定要解锁，否则后续会一直在等待。

还是要仔细阅读文档和示例，理解流程，https://wendux.github.io/dist/#/doc/flyio/interceptor

**Comment by JH46666** [comment]
> fly.lock 是锁定后续网路请求, 不包括本次，但拦截器支持异步任务，所以在本次请求发起前我们发现token过期的化，可以先请求token，然后更新token，在将更新后的`request`对象返回，继续本次请求。相当于本次请求中间插了一次更新token的请求。 所以上面代码有两个问题：
> 
> 1. 在FlyLogin()登录成功后要设置header cookie;
> 
> ```js
>  return FlyLogin().then(res => {
>    console.log('res', res, cookies); //res已经有值了，cookies还没有为空
>   // 登录成功后在这里也要设置header
>    request.headers["Cookie"] = cookies;
>    return request; //返回request是表示使用这个request对象继续上一次请求
> })
> ```
> 
> 1. 登录成功后一定要解锁，否则后续会一直在等待。
> 
> 还是要仔细阅读文档和示例，理解流程，https://wendux.github.io/dist/#/doc/flyio/interceptor

FlyLogin()如果是哥async，await呢，

**Comment by JH46666** [comment]
> > fly.lock 是锁定后续网路请求, 不包括本次，但拦截器支持异步任务，所以在本次请求发起前我们发现token过期的化，可以先请求token，然后更新token，在将更新后的`request`对象返回，继续本次请求。相当于本次请求中间插了一次更新token的请求。 所以上面代码有两个问题：
> > 
> > 1. 在FlyLogin()登录成功后要设置header cookie;
> > 
> > ```js
> >  return FlyLogin().then(res => {
> >    console.log('res', res, cookies); //res已经有值了，cookies还没有为空
> >   // 登录成功后在这里也要设置header
> >    request.headers["Cookie"] = cookies;
> >    return request; //返回request是表示使用这个request对象继续上一次请求
> > })
> > ```
> > 
> > 
> > 
> > 1. 登录成功后一定要解锁，否则后续会一直在等待。
> > 
> > 还是要仔细阅读文档和示例，理解流程，https://wendux.github.io/dist/#/doc/flyio/interceptor
> 
> FlyLogin()如果是个async，await呢，

    console.log('login: ', login());
     let wyqn =  new Promsie((resolve, reject)=>{
       resolve(()=>{
         login();
       })
      })
      return wyqn().then((d)=>{
        console.log('d: ', d);
      return request; //只有最终返回request对象时，原来的请求才会继续
    }).finally(() => {
      fly.unlock();//解锁后，会继续发起请求队列中的任务，详情见后面文档
    })

**Comment by wendux** [comment]
async本质上也是返回future，只不过一个语法糖，没有本质区别
