### ISSUE TITLE
希望适配百度小程序和头条小程序

### ISSUE THREAD

**Issue by ivanlee93** [wendux/fly#193]
![image](https://user-images.githubusercontent.com/22174857/52830579-4f38c580-310c-11e9-87b3-8372c73124c3.png)
我用uni-app，开发了一套代码。现在View层都可以复用了，就是数据请求用fly还差百度小程序和头条小程序

**Comment by wendux** [comment]
可以自己参考源码写adapter适配

**Comment by ivanlee93** [comment]
恩，看了一下源码就是Copy下改个api和参数字段名就可以。https://github.com/wendux/fly/pull/218

**Comment by kid1412621** [comment]
所以还是不支持?
