### ISSUE TITLE
http请求delete方式传递参数格式错误

### ISSUE THREAD

**Issue by fffyang** [wendux/fly#194]
delete请求应该类似get请求数据体在query string parameters中，但是flyio的请求数据在request payload中，是类似于post请求了。
![image](https://user-images.githubusercontent.com/37098927/52995689-55a1a700-3456-11e9-9ddd-ec98f188d01a.png)

**Comment by clfuture** [comment]
您好，我有两个问题不太明白。
1、为什么delete请求的参数要放在query string parameters中呢？
2、怎么样可以让delete 请求的参数放在request payload中

不明白在哪里可以设置请求参数的位置，我这里有两个使用flyio的项目，但是一个项目的delete请求参数在body里，一个在url里，搞不懂了

**Comment by liusheng22** [comment]
👋 好消息！现在有一个**fork并优化的版本**完全解决了这个`DELETE`请求`body`参数的问题。

**包名:** [`flyio.js`](https://www.npmjs.com/package/flyio.js)

**安装:**
```bash
npm i flyio.js
```

**使用方法:**
```javascript
// 之前 (不工作,无法传递 body/payload 参数)
fly.delete('/sys/resource/op/batchDel',
  {
    ids: [1,2,3]
  }
)

// 现在 (完美工作,deleteWithBody 配置生效)
fly.delete('/sys/resource/op/batchDel',
  {
    id: [1,2,3]
  },
  {
    deleteWithBody: true
  }
)

// or 同时支持 query 参数和 body 参数

fly.delete(url, null, {
  params: { key: 'params-value' }, // 支持 query 参数
  body: { key: 'body-value' }, // 支持 body 参数
  deleteWithBody: true // 允许 DELETE 请求传递 body 参数
})
```

**文档:** [https://flyio-js.vercel.app/doc/flyio/delete-with-body](https://flyio-js.vercel.app/doc/flyio/delete-with-body)

**仓库:** [flyio.js](https://github.com/liusheng22/flyio)

这个新`npm`包保持了100%的向`fly.js`兼容性，同时添加了缺失的`deleteWithBody`功能。试试看吧！🚀
