### ISSUE TITLE
支付宝小程序版本的扩展存在一定不足，希望后续处理！

### ISSUE THREAD

**Issue by rockywu** [wendux/fly#195]
https://github.com/wendux/fly/blob/768c1db6d76db8fa6a0015d017dea3bc8a61e7f9/src/adapter/ap.js#L13

本次版本合并只支持text格式，对于通用的接口请求应该补充json配置
支付宝小程序文档：
-- | -- | -- | --
dataType | String | 否 | 期望返回的数据格式，默认json，支持json，text，base64
https://docs.alipay.com/mini/api/network

**Comment by wendux** [comment]
因为fly也会自动转json，所以底层统一接收以字符串形式接收，避免二次parse
