### ISSUE TITLE
fly.js中对readyStatus判断的疑问

### ISSUE THREAD

**Issue by memoryjin** [wendux/fly#2]
为啥没有判断304的情况，这时候直接走到reject了啊......

**Comment by wendux** [comment]
http状态码是2xx时为成功状态   3xx 4xx 5xx 都会走到reject 这是正常逻辑

**Comment by wendux** [comment]
已修复 https://github.com/wendux/fly/pull/6

**Comment by wendux** [comment]
补充：浏览器状态是304时，会存本地缓存加载，但是浏览器传给xhr的状态依然是200，所以在ajax中是不会出现304的。由于这个特性现在并没有在所有浏览器上验证，为了保险期前，fly现在添加了304的判断逻辑，将来可能会去掉。
