### ISSUE TITLE
请问小程序端 如何结合async await使用呢

### ISSUE THREAD

**Issue by bbRangers** [wendux/fly#201]
请问小程序端 如何结合async await使用呢

**Comment by chlshown** [comment]
顶

**Comment by bbRangers** [comment]
> 顶

简单封装一下就行 很简单的

**Comment by chlshown** [comment]
请问有案例么？或者说下思路？谢谢！

**Comment by bbRangers** [comment]
> 请问有案例么？或者说下思路？谢谢！

get(url, data, that) {
    return new Promise(function(resolve, reject) {
      (async () => {
        that.$fly.get(url,data)
        .then((res)=>{
          resolve(res);
        }).catch(err=>{
          resolve(err);
          console.log(err)
        })
      })();
    });
  },

........ 给

**Comment by chlshown** [comment]
function testPromise() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log('Promise handle')
          resolve(123)
        }, 2000)
      })
    }

   async function testAsync() {
      const result = await testPromise()
      console.log('async test--', result)
    }

    testAsync()

报错：regeneratorRuntime is not defined

**Comment by chlshown** [comment]
我加了facabook的这个runtime库，但是这个库本身又报了另外的错

**Comment by PillarChen** [comment]
好


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
