### ISSUE TITLE
拦截器 token 过期时重复请求，请问如何解决？

### ISSUE THREAD

**Issue by CherishLyf** [wendux/fly#223]
场景：登录态过期时，拦截器拦截，重复请求 getToken 接口

我的代码：
![image](https://user-images.githubusercontent.com/13624554/59743115-e58b1c80-92a1-11e9-836a-ac694b53303e.png)
![image](https://user-images.githubusercontent.com/13624554/59743162-05224500-92a2-11e9-9715-ef991091a2de.png)

问题：不知道为什么这里 lock() 没有生效，是我写错了吗？导致重复请求
期望：期望找到问题所在，最好能提供一个解决思路~~

**Comment by lkangd** [comment]
@CherishLyf 遇到同样的问题了，请问是怎么解决的？

**Comment by CherishLyf** [comment]
this.func1()
      .then(() => {
        return this.func2()
      })
      .then(() => {
        return this.func3()
      })

**Comment by CherishLyf** [comment]
@CurtisLiong 
this.func1()
.then(() => {
  return this.func2()
})
.then(() => {
  return this.func3()
})
我这样解决的

**Comment by lkangd** [comment]
@CherishLyf 你的意思是你在业务逻辑层做了处理？没在拦截器里面 lock？

**Comment by CherishLyf** [comment]
@CurtisLiong 
拦截器里也 lock 了，我当时的问题是同一个页面多个请求，导致重复请求，不知道你是什么问题？拦截没生效吗？

**Comment by lkangd** [comment]
@CherishLyf 我的问题是两个并发请求，同时过期，然后在 response 的 error 里面 lock 了，但是拉新 token 的请求还是发了两次，没有 lock 住。

**Comment by CherishLyf** [comment]
@CurtisLiong 应该跟我问题一样 你业务层用链式调用试试 没用的话 可能是拦截那里写得有问题 可以再看看文档比照下

**Comment by lkangd** [comment]
@CherishLyf 我知道原因了，刚刚直接在 `response` 的里面使用 `fly.lock()`是不对的，我用了箭头函数， `fly.lock`是`fly.interceptors.request.lock`的别名，所以在 response 里面话，我应该用`fly.interceptors.response.lock`

**Comment by lkangd** [comment]
@CherishLyf 你的问题应该也是一样的。你看看。`https://wendux.github.io/dist/#/doc/flyio/interceptor`
