### ISSUE TITLE
能否把各个端的引入和初始化统一起来

### ISSUE THREAD

**Issue by mario-huang** [wendux/fly#224]
现在node端TS里面需要：
import Fly from 'flyio'
const fly = Fly
Fly本身已经初始化了。
微信端
import Fly from 'flyio'
const fly = new Fly() // Fly需要new

搞得我们的SDK基于fly，写代码的时候是node环境，但到了微信小程序环境就报错了。

**Comment by kyleYang** [comment]
我想问下，在TS里面怎么用Fly。尝试了好多种写法都不行。 主要是说在小程序里面
