### ISSUE TITLE
feature:目前的公共header配置支持动态配置吗？

### ISSUE THREAD

**Issue by vsona** [wendux/fly#23]
feature:
目前的公共header配置支持动态配置吗?

如果不支持 是否有这个必要支持一下？

还有目前支持设置公共的body吗？

如果不支持是否有必要支持一下？

**Comment by wendux** [comment]
1. 动态配置公共头是支持的，您可以在代码中任何地方动态设置公共请求头, 如下:
```javascript 
fly.config.headers["xx"]="xyz"
```
注意：**设置公共请求头会对该fly实例发起的所有请求生效**，如果你是想实现某次请求使用特定的请求头的话，不应该去动态改公共的请求头，而是应该设置本次请求的头，如：
```javascript
fly.post(url,data,{
   headers:{xx:"xyz"}
})
```
2. 如果您想添加公共body, 可以通过请求拦截器去添加公共body，请求拦截器对该fly实例发起的所有请求有效，如：
```javascript
fly.interceptors.request.use((config)=>{
 var wrapBody={
  common:{...},  //公共body
  body:config.body  //本次请求body
 }
 config.body=wrapBody
})
```

**Comment by vsona** [comment]
我们是这种 token作为公共参数放到header里面，但是又不能写死 只能动态获取，因为token随时会刷新或者踢票。如果每个接口都单独加上 又显得麻烦。
```javascript
  context.params = {
    ...{
      version,
      subVersion,
      channelType,
      token: accountService.getToken()
    },
    ...context.params
  }
```
这样的话 目前就只能在公共的request拦截里面 注入token到headers里面了。
fly.config.headers的设置可以考虑这种:
```javascript
export const promoteValue = (target = {}, funcArgs = []) => {
  if (typeof target === 'object') {
    return target
  }
  if (typeof target === 'function') {
    return target(...funcArgs)
  }
}
```

**Comment by vsona** [comment]
@wendux 还有个疑问想了很久不明白。
```javascript
            var rqiPromise;
            if (rqi.handler) {
                rqiPromise = rqi.handler(options, Promise) || options;
            }
```
这里 如果在handler里面调用 ```promise.resolve('haha')```

在请求的then里面会接收到 ```haha```

我看handler传参是```Promise```, Promise.resolve()应该是返回一个新的Promise对象呀？

怎么会改变外层promise的状态导致直接resolve呢？

应该是继续往下走了，options的值是```haha```
```javascript
            rqiPromise.then((options) => {
                // Normalize the request url
                url = utils.trim(options.url);
                var baseUrl = utils.trim(options.baseURL || "");
                if (!url && isBrowser && !baseUrl) url = location.href;
```

**Comment by wendux** [comment]
1. 如果你要动态在header中设置token, 可以：
```javascript
   fly.config.headers.token="xxx"
```
这样不需要在拦截器里面设置啊，不是很明白你的意思。
2. 在handler中返回 `promise.resolve('haha')`后，是应该直接终止本次请求，将'haha'作为本次请求返回的的数据，这块有问题，已修复，请将fly升级到>=0.3.6.

**Comment by vsona** [comment]
1. 
```javascript
   fly.config.headers.token="xxx"
```
这样设置token 每次我token改变都要主动重新同步一下fly里面保存的token。

比如我清除了本地token，那就要执行
```javascript
delete fly.config.headers.token
```
如果又重新登录了 那还要在登录成功的代码里加上
```javascript
fly.config.headers.token = getToken()
```
数据流不应该这样。应该是每个请求在组装的时候都主动获取一次token。
比如这样:
```javascript
fly.config.headers = () => {
    token: getToken(),
    version: 1.0.2
}
```
2. 原来是代码没更新。我看了好久。新版代码就对了:joy:
