### ISSUE TITLE
请求地址后拼参数有问题

### ISSUE THREAD

**Issue by RamirezET** [wendux/fly#265]
![image](https://user-images.githubusercontent.com/7698302/94404432-9371c000-01a1-11eb-9305-63f837308bb6.png)

如图，我的请求是delete方法，你的注释里写着只有在get请求才拼接参数，但代码并未对请求方式进行判断，全部拼接了参数

**Comment by RamirezET** [comment]
经查阅··是我们后台人员对DELETE方法理解有误  DELETE方法按理说确实应该拼接在地址栏

**Comment by liusheng22** [comment]
👋 好消息！现在有一个**fork并优化的版本**完全解决了这个`DELETE`请求`body`参数的问题。

**包名:** [`flyio.js`](https://www.npmjs.com/package/flyio.js)

**安装:**
```bash
npm i flyio.js
```

**使用方法:**
```javascript
// 之前 (不工作,无法传递 body/payload 参数)
fly.delete('/sys/resource/op/batchDel',
  {
    ids: [1,2,3]
  }
)

// 现在 (完美工作,deleteWithBody 配置生效)
fly.delete('/sys/resource/op/batchDel',
  {
    id: [1,2,3]
  },
  {
    deleteWithBody: true
  }
)

// or 同时支持 query 参数和 body 参数

fly.delete(url, null, {
  params: { key: 'params-value' }, // 支持 query 参数
  body: { key: 'body-value' }, // 支持 body 参数
  deleteWithBody: true // 允许 DELETE 请求传递 body 参数
})
```

**文档:** [https://flyio-js.vercel.app/doc/flyio/delete-with-body](https://flyio-js.vercel.app/doc/flyio/delete-with-body)

**仓库:** [flyio.js](https://github.com/liusheng22/flyio)

这个新`npm`包保持了100%的向`fly.js`兼容性，同时添加了缺失的`deleteWithBody`功能。试试看吧！🚀
