### ISSUE TITLE
post的在小程序里面的问题

### ISSUE THREAD

**Issue by shiweiqi19930328** [wendux/fly#28]
post的在小程序里面为什么Content-Type不是application/x-www-form-urlencoded，而变成了application/json

**Comment by wendux** [comment]
如果请求数据是一个json对象, Content-Type会是application/json，如果要使用application/x-www-form-urlencoded编码，有两种方法：
1.  请参照使用[application/x-www-form-urlencoded](https://github.com/wendux/fly/blob/master/README-CH.md#%E4%BD%BF%E7%94%A8applicationx-www-form-urlencoded-%E7%BC%96%E7%A0%81)
2. 在请求拦截器中将json对象转成编码后的字符串。
