### ISSUE TITLE
跨域请求

### ISSUE THREAD

**Issue by Miriring** [wendux/fly#3]
能够支持Jsonp吗

**Comment by wendux** [comment]
fly不会支持jsonp，原因有三点：

1. 由于jsonp本质上是通过可跨域html标签来完成的，并非通过http engine (XmlHttprequest)来完成. 实现其实是dom操作。
2. jsonp只是在浏览器环境中需要，而其它环境可能并不存在dom。
3. 在fly中，如果您有跨域需求，使用CORS会更简单。
