### ISSUE TITLE
weex 中

### ISSUE THREAD

**Issue by czboosj** [wendux/fly#31]
let stream = weex.requireModule('stream');
var modal = weex.requireModule('modal')
var Fly = require("flyio/dist/npm/weex")

var fly=new Fly

export  default {
  methods:{

    /*是否iphoneX*/
    isIpx() {
      return weex && (weex.config.env.deviceModel === 'iPhone10,3' || weex.config.env.deviceModel === 'iPhone10,6');
    },

    flyGET(api, callback){
      modal.toast({message: '加载fly'})
      return fly.get(api).then(callback)
    },

get 没有反应, 怎么回事,

**Comment by wendux** [comment]
已修复，升级flyio>=0.4.0
