### ISSUE TITLE
依赖找不到fs net tls dgram dns

### ISSUE THREAD

**Issue by eeeeeeeason** [wendux/fly#33]
直接使用其他人项目run dev没事。但我自己的项目重装了flyio多次之后还是跑不动啊。。require('flyio')就报错
![flyio](https://user-images.githubusercontent.com/27959851/37877218-285915e2-308a-11e8-8fbc-59d9baa9be7c.png)

**Comment by eeeeeeeason** [comment]
辛苦了。虽然我可以直接在其他人的包基础上开发但还是想知道问题所在

**Comment by wendux** [comment]
你这看起来貌似是依赖的问题，可以将node_modules文件夹删掉然后`npm install`重装一下依赖试试吧。

**Comment by wendux** [comment]
#36
