### ISSUE TITLE
请求错误返回的Error事例里，希望将response body加进去

### ISSUE THREAD

**Issue by sousuo28** [wendux/fly#34]
因为没有使用独立的业务错误码，而是将错误归类到了http error里，并将一些错误信息写入body返回。因此需要在请求错误的信息里拿到body。谢谢！

**Comment by wendux** [comment]
是可以通过`engine`取到错误时的响应内容的:
```javascript
err.engine.responseText
```

**Comment by sousuo28** [comment]
@wendux 抱歉，是我的错。看了一下，都可以在engine里拿到。直接拿engine.response就拿到body了。谢谢！ 正在用fly替换zepto里的ajax 😁
