### ISSUE TITLE
npm引入fiyio失败

### ISSUE THREAD

**Issue by vino1994** [wendux/fly#36]
![image](https://user-images.githubusercontent.com/18673381/37898631-e872bc2a-311b-11e8-818d-404c83b60d08.png)
按照提示继续安装完后，依然提示失败
![image](https://user-images.githubusercontent.com/18673381/37898732-2b84943e-311c-11e8-8ce4-c66695dfa7bd.png)
node版本  v8.9.3
npm版本   v5.6.0

**Comment by vino1994** [comment]
将整个mode_modules包删掉之后重新npm install也不行

**Comment by wendux** [comment]
是node工程吗？

**Comment by vino1994** [comment]
不是的，是mpvue，我在https://github.com/Meituan-Dianping/mpvue/issues/109看到了大佬们的对话，好像npm完了之后不能直接引入要先在webpack里面的alias设置一下，然后才可以import进来使用，比知道理解的对不对？

**Comment by wendux** [comment]
检查查flyio的入口文件引用是否正确，flyio对于不同的平台，入口文件有的会不同，比如，如果你是微信小程序工程，就应该引入小程序的入口文件:
```javascript
 var Fly=require("flyio/dist/npm/wx")//微信小程序入口
```

**Comment by vino1994** [comment]
感谢~

**Comment by cmideal** [comment]
好像还是有问题，mpvue的标准格式有没有呢，这个说的不清楚啊

**Comment by wendux** [comment]
@cmideal  mpvue中使用示例请参考 #35
