### ISSUE TITLE
在请求拦截器中设置请求body ，打印出来是已经改变的，但是请求发出去的数据为什么没有发生改变呢

### ISSUE THREAD

**Issue by duanpf** [wendux/fly#43]
![1523159538 1](https://user-images.githubusercontent.com/24790085/38463057-98755996-3b23-11e8-8960-4a14348c90d0.jpg)
![1523159583 1](https://user-images.githubusercontent.com/24790085/38463060-9c356684-3b23-11e8-8ba8-79616b5d6922.jpg)
![1523159604 1](https://user-images.githubusercontent.com/24790085/38463059-9b848f1c-3b23-11e8-85f2-a7491b930d63.png)

**Comment by wendux** [comment]
已修复，请升级到版本>=0.4.7

**Comment by duanpf** [comment]
请问下，您是在源文件的哪里做了处理呢

**Comment by wendux** [comment]
请升级到0.4.8，源代码之前在进入拦截器之前将body缓存到了一个`data`变量里了，发送时发送的是`data`，所以未生效，0.4.8在经过拦截器之后又将`body`同步到了`data`.
