### ISSUE TITLE
小程序中引入flyio/dist/npm/wx报错

### ISSUE THREAD

**Issue by richie523** [wendux/fly#46]
thirdScriptError 
 sdk uncaught third Error 
 __w is not defined 
 ReferenceError: __w is not defined

在mpvue项目中引入，出现错误

**Comment by F-loat** [comment]
#45

**Comment by wendux** [comment]
@richie523 使用的是哪个版本？是0.4.8吗？

**Comment by richie523** [comment]
是0.4.8，我require('flyio/dist/umd/wx.umd.min')是可以的

**Comment by wendux** [comment]
已修复，请升级到0.4.9

**Comment by chenbool** [comment]
在mpvue报错， "flyio": "^0.6.5",

**Comment by chenbool** [comment]
thirdScriptError 
 sdk uncaught third Error 
 Fly is not defined 
 ReferenceError: Fly is not defined
在mpvue报错
版本0.6.5

**Comment by chenbool** [comment]
只有在 0.6.0 以下的版本不报错，建议大家安装 <= 0.5.9
