### ISSUE TITLE
对restFul支持问题

### ISSUE THREAD

**Issue by wujianping334455** [wendux/fly#47]
由于小程序的wx.request使用不了patch方法，简单封装wx.request的话，并不能使用patch方法，看到Fly文档说有说到可以用使用patch方法。怎么才能让它支持使用patch方法呢？是需求我自己更换别的http引擎吗？求解。

**Comment by wendux** [comment]
由于微信小程序平台API不支持patch方法，所以fly目前也无法支持，等小程序原生支持后，fly会第一时间同步。
