### ISSUE TITLE
mpvue中使用fly，如何传额外参数进拦截器？

### ISSUE THREAD

**Issue by xlkit456852** [wendux/fly#48]
在request拦截器中，可以弹出loading提高用户体验，这很棒。
但我在实际项目中，有的请求需要弹出loading，有的请求不需要，可以在发起请求的时候传一些参数进拦截器，拦截器再根据这个参数判断是否要显示loding这样吗？比如说：
```
fly.get(url,params,{isShowLoading:false});
```
不知有没有类似的解决方法？

**Comment by wendux** [comment]
这种方式fly 本来就支持。
