### ISSUE TITLE
ie10 报错 InvalidStateError

### ISSUE THREAD

**Issue by shawchen08** [wendux/fly#5]
从网上找到的解决方案是：[在设置responseType之前执行一次engine.open()](https://connect.microsoft.com/IE/feedback/details/795580/ie11-xmlhttprequest-incorrectly-throws-invalidstateerror-when-setasasting-responsetype)。
这里是不是可以把responseType的设置挪到engine.open()后面。

**Comment by wendux** [comment]
最新的代码已更新，你试试

**Comment by shawchen08** [comment]
可以了
