### ISSUE TITLE
微信小程序后端接收不到我传的参数

### ISSUE THREAD

**Issue by zcwk** [wendux/fly#50]
原因是:
Content-Type:"application/json;charset=utf-8"

网上都说要改成
Content-Type:"application/x-www-form-urlencoded"

**Comment by happybobo** [comment]
好好看文档。文档写了：

> Fly默认会将JavaScript objects 序列化为 JSON 发送（RequestBody），如果想以 application/x-www-form-urlencoded 编码格式发送，你可以使用如下方式：
