### ISSUE TITLE
mpvue下使用flyio报  dependencies were not found

### ISSUE THREAD

**Issue by YanYuanFE** [wendux/fly#53]
![image](https://user-images.githubusercontent.com/17774285/39026586-81a4394c-4480-11e8-95c9-ca1c4be8eded.png)
![image](https://user-images.githubusercontent.com/17774285/39026612-94e0086a-4480-11e8-826f-517fe99d6092.png)
OS： Ubuntu16.04
node：v9.11.1

**Comment by wendux** [comment]
入口文件引用不对，请仔细看文档 。 可以参阅#33

**Comment by YanYuanFE** [comment]
https://github.com/mini-mpvue/mpvue-douban-movie/blob/master/src/utils/request.js,

谢谢解答，想问下这个mpvue项目是也是这样引用入口的，怎么没有报错呢？

**Comment by wendux** [comment]
这是通过webpack alias 来自动选择的, 可以看这个工程下 webpack.base.conf.js 中相关配置：
```javascript
    alias: {
      'vue': 'mpvue',
      '@': resolve('src'),
      'flyio': 'flyio/dist/npm/wx',
      'wx': resolve('src/utils/wx')
    }
```
