### ISSUE TITLE
get请求多个key相同的query，比如query=a&query=b

### ISSUE THREAD

**Issue by sousuo28** [wendux/fly#54]
求教：如果使用`fly.get(url,{query:[a,b]})`，出来的请求是`url?query=[a,b]`，怎么传data才能转换成
`url?query=a&query=b`呢

**Comment by wendux** [comment]
只能传字符串了

**Comment by sousuo28** [comment]
我的问题可能和这个[issue #26](https://github.com/wendux/fly/pull/26)是一个意思？
我可以提一个pr，来增加响应的配置项和转换么？
```javascript
{
   parseJson: true,  // 现有配置是否转换response body的
   serializeBody: true // 新增配置是否转换get请求的request body。设置为true则合并url-query和body
}
```

**Comment by wendux** [comment]
这个可以在请求拦截器中做，如果要放在框架里，得考虑几个问题：合并以什么规则合并？是否具有通用性？

**Comment by sousuo28** [comment]
@wendux 确实，需要考虑的情况比较复杂

**Comment by Airkro** [comment]
通用性的话，qs这个库用的最多。通过配置参数，常规的serialize效果和题主想要的serialize效果都有。不过要在fly里面使用要写进拦截器了
