### ISSUE TITLE
mpvue全局使用fly应该怎么配置，试了好几种方式都不行，求解答

### ISSUE THREAD

**Issue by godpan** [wendux/fly#58]
mpvue全局使用fly应该怎么配置，试了好几种方式都不行，求解答

**Comment by sousuo28** [comment]
1. 采用npm方式安装，`npm install flyio --save`
2. 在webpack.base文件中，设置alias：
```
alias: {
...
flyio: 'flyio/dist/npm/wx',
...
}
```
3. 创建文件`request.js`，命名无所谓，然后在其中进行全局配置
```
import Fly from 'flyio'

const request = new Fly()

// 可以进行拦截器、全局config等等设置

export default request
```

另外，可参考IT之家的非常棒的开源小程序项目：[github地址](https://github.com/F-loat/ithome-lite.git)

**Comment by godpan** [comment]
很好的解决了我的问题，使用方式很棒，万分感谢。
