### ISSUE TITLE
cookie和headers["set-cookie"]合并异常

### ISSUE THREAD

**Issue by ltinyho** [wendux/fly#60]
```
fly.interceptors.request.use((request) => {
  const token = loginStorage.getToken();
  if (token) {
    request.headers.cookie = `token=${token}`;
  }
});
```
在拦截器中设置cookie，如果不加`;`的话`token=${token};`，会把`headers["set-cookie"]`合并,变成例如`token=${token},sessionId=11d5b3577e42e10eade71a07b4a1148f `,就是会把cookie拼接

**Comment by wendux** [comment]
按照http协议标准，请求头中的"cookie"只能有一项，所以会拼接，另外http请求头中没有"set-cookie"字段的，"set-cookie"是在响应头中，并可以有多项。

**Comment by yuangu** [comment]
我试了一下，我用 console.log(typeof(response.headers['set-cookie'])); 打印一下类型，还是string 类型。我用的是node

**Comment by yuangu** [comment]
刚刚你给我了思路，然后我去查了一下代码。node返回来的Set-Cookie确实是一个数组。但是在engine-wrapper.js里的getResponseHeader，确实把它转为了string，然后再去fly.js里.split("\r\n");  ^_^

**Comment by LitteFlower** [comment]
> 当响应头里有多个set-cookie的时候，会用,去合并。例如微博的：
> 
> ```
>  'SSOLoginState=1536134288; path=/; domain=.weibo.com,SUB=_2A252i_zADeRhGedG71YY8CrFyjiIHXVSd4SIrDV8PUJbkNBeLRGikW1NUT14sVzIzh9I1_FfRD5PFyqywqC3rBJI; Path=/; Domain=.weibo.com; Expires=Thu, 05 Sep 2019 07:58:08 GMT; HttpOnly,SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WhmSd4.JMY.FapQYjBFs41u5JpX5oz75NHD95Qp1hBX1K5X1K2XWs4Dqcj_i--ciKLhi-iWi--ciK.4i-iWi--NiKLWiKnXi--fiKnfiKn0i--Ri-z7i-zN; expires=Thursday, 05-Sep-2019 07:58:08 GMT; path=/; domain=.weibo.com'
> ```
> 可以看到HttpOnly后面居然还接了一个,

遇到这种情况，正常前端怎样返回cookie给服务端，以什么样的格式

**Comment by yuangu** [comment]
@LitteFlower 好像新版本已经改了，返回的是一个list类型（数组类型）。

**Comment by LitteFlower** [comment]
> @LitteFlower 好像新版本已经改了，返回的是一个list类型（数组类型）。

cookie的数组拿到了，但是请求头是以逗号（，）隔开吗

**Comment by LitteFlower** [comment]
> @LitteFlower 好像新版本已经改了，返回的是一个list类型（数组类型）。

cookie的数组拿到了，怎么加到请求头上
