### ISSUE TITLE
ie9 post “参数无效”

### ISSUE THREAD

**Issue by missy0u** [wendux/fly#66]
0.5.7

ie9 post

![image](https://user-images.githubusercontent.com/3926664/40175242-147135ce-5a0a-11e8-8fff-3d995c3f17f9.png)

**Comment by wendux** [comment]
貌似是你设置了不被支持的header, 你都设置了哪些header字段？

**Comment by missy0u** [comment]
fly没有设置header

![image](https://user-images.githubusercontent.com/3926664/40289412-b6163716-5cea-11e8-9880-ad84c2faf521.png)

**Comment by wendux** [comment]
不是这个，是http header, 你设置header了吗？

**Comment by missy0u** [comment]
没有设置过任何header，其它都没问题，就只有ie9报错。。。

**Comment by zhyc9de** [comment]
这个问题我提交pr了，原因可能是某些版本的IE9才会出现，items会解析出一个最后一个元素为空串的列表，getResponseHeader参数为空串的时候会报“参数错误”这个问题。另外我在IE中还遇到了另外一个问题，在pr的commit中提到了

**Comment by wendux** [comment]
fixed e375c3ca5be0362bbb189745cb1dcd6805e15541
Please update to `0.6.0` to verify.
