### ISSUE TITLE
微信小程序POST正文使用urlencode编码的问题

### ISSUE THREAD

**Issue by frapples** [wendux/fly#67]
相关依赖：
```json
  "dependencies": {
    "flyio": "^0.5.4",
    "mpvue": "^1.0.10",
    "qs": "^6.5.2",
    "vuex": "^2.3.1"
  },
```

代码：
```js
import Fly from "flyio/dist/npm/wx";
import qs from "qs";


let fly = new Fly; 
fly.config.baseURL="http://127.0.0.1:8181/";
fly.interceptors.request.use((request, promise)=>{
    if (request.method == "POST") {
        request.headers["Content-Type"] = "application/x-www-form-urlencoded";
        // 经测试设置header后已经被库自动编码了
        // request.body = qs.stringify(request.body);
    }
    return request;
}); 

export function network() {
    return fly;
}
```

经过测试：
1. https://github.com/wendux/fly/issues/13 中，您提到`fly会在发送的数据是字符串时将 Content-type设置为application/x-www-form-urlencoded`，但是我在没有设置interceptor时，调用`fly.post('/api/xxx', qs.stringify(data))`发现，Content-Type仍然是`application/json;charset=UTF-8`。
2. https://github.com/wendux/fly/issues/13 中，您提到`flyio RequestBody默认以json形式传递数据，如果非要以formdata编码传递的话，需要手动编码`，但是经过测试，在interceptor手动设置Content-Type后，hash表数据会被自动urlencode编码，如果使用qs额外编码会导致重复编码（代码中被注释的行）。
3. 如何能自定义上述自动urlencode编码的行为？hash表中对于null字段我期望的行为是不将其作为数据带上，但是库的行为是将其作为undefined字符串带上。

**Comment by wendux** [comment]
请升级到0.5.8重试

**Comment by ZevinChen** [comment]
上述第三个问题我也遇到了，采用
`.request({
                    method: "get", // post/get 请求方式
                    url: "",
                    body: {}
                })`
的方式请求，参数值为汉字的会自动编码，后台还得处理多一次，怎么去掉这个自动编码
