### ISSUE TITLE
小程序不支持 finally 

### ISSUE THREAD

**Issue by zaxlct** [wendux/fly#71]
文档中的 fly.unlock() 没办法调用
```
finally(() => fly.unlock()) 
```

**Comment by wendux** [comment]
不支持finally 的话你可以在then和catch 中分别调用一下即可

**Comment by kid1412621** [comment]
![image](https://user-images.githubusercontent.com/26278054/58618521-6daa8180-82f5-11e9-9874-19ede30befd5.png)
@wendux 能否做下兼容? 不然老报错
