### ISSUE TITLE
能否考虑加一个类似.always的方法

### ISSUE THREAD

**Issue by zhaohuanlei** [wendux/fly#75]
.then(function() {
    alert( "success" );
  })
  .catch(function() {
    alert( "error" );
  })
  .always(function() {
    alert( "complete" );
  })

之前用jQuery的ajax时候，这个方法还是很实用的，无论什么请求结果，都会执行该方法。

**Comment by wendux** [comment]
fly所有请求api返回的都是一个`Promise`对象，现在ES标准里`Promise`对象已经有`finally`方法了。
