### ISSUE TITLE
flyio 上传文件失败 （不是nodeJS 上传），是h5 spa 和小程序 都不能上传文件

### ISSUE THREAD

**Issue by Eden-Harris** [wendux/fly#76]
> flyio 上传文件失败 （不是nodeJS 上传），是vue spa 和小程序 都不能上传文件。这个问题之前一直都有在issue看到，但是一直没有解决办法，问mpvue群大家也都不知道，上传文件都用了wx.uploadFile(). 但是可以使用 flyio 实现文件上传吗？（不是nodejs上传，是小程序和H5页面）

**Comment by wendux** [comment]
@Eden-Harris h5中可以通过formdata ,小程序中fly暂不支持，可以考虑将文件进行base64 编码后再用fly提交。
