### ISSUE TITLE
Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by pikeCol** [wendux/fly#79]
i am not setting headers but the defaut header is below.
![image](https://user-images.githubusercontent.com/20314304/40827904-a6f7ce82-65b1-11e8-9f6a-dbe8bdeabab7.png)

my  post method:
![image](https://user-images.githubusercontent.com/20314304/40827966-e2f73b66-65b1-11e8-9be0-1f0f8d51aa11.png)

**Comment by wendux** [comment]
If you send Json  data to sever ,   fly  will set `content-type`   value  `application/json` automatically unless you set it explicitly.
