### ISSUE TITLE
作者考虑下支持ie低版本浏览器不？

### ISSUE THREAD

**Issue by hyingreborn** [wendux/fly#8]
目前正在用一款支持低版本IE的mvvm框架(yoxjs)，ajax还在用jquery的。
如果配合上fly，就可以安心删掉jquery了...

**Comment by wendux** [comment]
IE<9 以下没有支持计划，原因有两点：
1. 兼容代码过多会违背fly定位为轻量级的目标
2. ie8下catch为关键字， promise的catch 方法不能正常使用

**Comment by yuu2lee4** [comment]
@hyingreborn jq的ajax应该可以单独拿出来
