### ISSUE TITLE
post 方法传入 data 的时候 Request Method 不正确

### ISSUE THREAD

**Issue by stxwd46** [wendux/fly#80]
## 一. 问题描述
      调用 post api，按文档的实例，传入 url 和 data 之后，请求里显示 Request Method 为 OPTIONS
  
## 二. 可复现代码
      
      fly.post('/user', {
        name: 'Doris',
        age: 24
        phone:"18513222525"
      })
      .then(function (response) {
        console.log(response);
      })
     .catch(function (error) {
       console.log(error);
      });

## 三. 错误截图
![image](https://user-images.githubusercontent.com/7361933/40894352-7ad50708-67db-11e8-8741-93f03a3ac3f0.png)

**Comment by wendux** [comment]
这是正常的，对于跨域非简单请求浏览器都会发起一次预检请求，详情可以查看MDN文档。

**Comment by stxwd46** [comment]
所以解决方法可否参照你的另一个示例，通过制定 content-type 让其变为简单请求来解决这个问题呢

```js
fly.post('/user', {
  name: 'Doris',
  age: 24
  phone:"18513222525"
}, {
  headers:{
    "content-type":"application/x-www-form-urlencoded"
  }
});
```

**Comment by wendux** [comment]
关于简单请求的定义可参考mdn文档。本条issue 先关闭。
