### ISSUE TITLE
在mpvue中捕获不了异常

### ISSUE THREAD

**Issue by anpoz** [wendux/fly#84]
// try {
    //   let res = await api.getNextTask()
    //   commit('updateTask', res.data)
    // } catch (err) {
    //   console.log(err)
    // }
    api
      .getNextTask()
      .then(res => {
        commit('updateTask', res.data)
      })
      .catch(err => {
        console.log(err)
      })

![qq 20180616200335](https://user-images.githubusercontent.com/2825342/41498439-7e1ce6f0-71a0-11e8-93c4-8ec46bebc0c1.png)

412应该是要进到拦截器错误处理部分，但却没有

**Comment by wendux** [comment]
贴出你的拦截器代码

**Comment by anpoz** [comment]
![qq 20180625102737](https://user-images.githubusercontent.com/2825342/41827527-809663de-7862-11e8-8b18-acebb67b2559.png)
![qq 20180625102814](https://user-images.githubusercontent.com/2825342/41827529-83269d1c-7862-11e8-9654-f9f176313258.png)

**Comment by wendux** [comment]
@anpoz  返回的数据是什么？ 你这个貌似是对返回的数据转化为json时出错了，看看返回的数据是否合法。

**Comment by anpoz** [comment]
数据是空的

**Comment by wendux** [comment]
fixed e375c3ca5be0362bbb189745cb1dcd6805e15541
Please update to `0.6.0` to verify.
