### ISSUE TITLE
请求异常在小程序能获取到response,在h5页面获取不到,不知道是不是跨域引起

### ISSUE THREAD

**Issue by lzyweb** [wendux/fly#87]
![image](https://user-images.githubusercontent.com/23628423/42011661-07affee6-7ac7-11e8-87c1-c542d43a0012.png)
![image](https://user-images.githubusercontent.com/23628423/42011701-37b7cba0-7ac7-11e8-88db-0dba9e51dacd.png)
![image](https://user-images.githubusercontent.com/23628423/42012110-3bc45ec8-7ac9-11e8-96ed-abdfb3235941.png)

**Comment by zhyc9de** [comment]
是的，服务端没有开启cors，导致跨域无法拿到response
