### ISSUE TITLE
设置请求都 content-type 不生效 

### ISSUE THREAD

**Issue by leanTim** [wendux/fly#90]
设置其他的 头都有效  设置 content-type 一直是 'application/json'

**Comment by wendux** [comment]
@leanTim 贴一下你设置和调用的代码


--[From gitme Android](http://flutterchina.club)

**Comment by leanTim** [comment]
```javascript
           fly.get({
                baseURL: 'https://douban.uieee.com/v2/movie/',
                url: sort,
                headers: {
                    'content-type': 'json',
                    'header-test': 'Noone'
                },
                // preseJson: true,
                timeout: 5000
            })
```
发现直接在 options 里直接设置`content-type` 是不生效的 但是后面的 `header-test` 却加到了请求头里~
 ![请求头](https://1-im.guokr.com/WX20180709-103636@2x.png)

最后是通过拦截器加上的这个头
```javascript
fly.interceptors.request.use((request)=>{
    //给所有请求添加自定义header
    request.headers["content-type"]="json";
     
    //可以显式返回request, 也可以不返回，没有返回值时拦截器中默认返回request
    return request;
})
```

**Comment by wendux** [comment]
get请求会忽略请求头中的"content-type"，这是因为get请求不会提交数据，所以也就无需指定提交数据的"content-type"，换成post、put就好了， 我很好奇你们什么场景会要改变get请求的"content-type"。

**Comment by liuhonga324** [comment]
我这边同样遇到这个问题，场景如下
上传文件到阿里云OSS，请求方式为PUT，要求将请求头的Content-Type改为文件的MIME，在单次请求中修改了options
_self.$http.request(uploadUrl, {data: file.path}, {method: 'PUT',  headers: {"content-type": 'image/*'}})
结果请求时请求头中的Content-Type仍为‘application/json;charset=UTF-8’
同样尝试了其他的MIME，如‘video/3gpp’, 也不生效
但是如果改为‘application/x-www-form-urlencoded’就是有效的

**Comment by wendux** [comment]
fixed e375c3ca5be0362bbb189745cb1dcd6805e15541
Please update to `0.6.0` to verify.
