### ISSUE TITLE
有默认的错误处理可配吗？

### ISSUE THREAD

**Issue by run27017** [wendux/fly#93]
就是当我忘记写catch的时候，有一个默认的错误处理的地方。例如：

    fly.defaultErrorHandler = function (error) {
      console.log('global catch error', error)
    }

然后如果是这样，打印"global catch error":

    fly.get('/url').then(response => console.log(response.data))

像下面这样，不会打印"global catch error"，而是打印"local catch error":

    fly.get('/url').then(response => console.log(response.data))
       .catch(error => console.log('local catch error', error)

**Comment by wendux** [comment]
并没有，因为如果promise reject之后没有catch的话，程序也不会终止，并且调试工具一般都会有提示，所以fly支持这个的必要性不大
