### ISSUE TITLE
在小程序中，query中key:value转换有误

### ISSUE THREAD

**Issue by Rayliwang** [wendux/fly#96]
在小程序中
```
const params = {
   criteria: {"lstudent.id":"1234"}
}
fly.get('/index',params)
```
http请求时Query String Parameter会转换成`criteria[lstudent.id]:4028814f64b72f080164b780b6450004`，实际应该是`criteria:{"lstudent.id":"4028814f64b72f080164b780b6450004"}`

**Comment by wendux** [comment]
@Rayliwang 不是的， 这种转换是对的，你value是个对象，按照formdata的编码方式，出来就是这样的，jQuery中就是这样。根据你的代码，看你应该是期望value是字符串，你把这个json对象转成字符串就行。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Rayliwang** [comment]
但是同样的传参，我用小程序和PC端的都可以正常使用，headers传参自段也是criteria:{"lstudent.id":"4028814f64b72f080164b780b6450004"}，只有用fly的时候是这样的criteria[lstudent.id]:4028814f64b72f080164b780b6450004

**Comment by wendux** [comment]
@Rayliwang  get请求参数为多级嵌套的对象时，fly对参数的处理策略和jQuery是一致的，都会进行一个编码(这样后台才能正常反序列话一个完整的json)，而不是简单的`toString`一下。如果你们的逻辑value需要的是一个字符串而不是一个json对象，那么你应该传字符串而不是对象。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
