### ISSUE TITLE
在微信小程序(mpvue)中，怎么实现token过期重新登录再重新请求业务接口的拦截器

### ISSUE THREAD

**Issue by gin280** [wendux/fly#97]

**Comment by ExcellentJR** [comment]
持续关注

**Comment by wendux** [comment]
@gin280 请参考文章中拦截器中的示例，一模一样的场景，几乎可以直接用的代码。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by yutao721** [comment]
参看一下这个https://juejin.cn/post/6940884603112538148
